baseURL = "https://visionary.top/"
languageCode = "en-us"
theme = "showfolio"
title = "VISIONARY"
EnableRobotstxt = true
images = ["images/profile.png"]
Paginate = 1000
darkMode = true
ignoreErrors = ["error-remote-getjson"]

[taxonomies]
series = "series"
tag = "tags"
category = "categories"

[params]
name = "Showfolio Theme"
author = "VISIONARY"
authorEmail = "min_0610@icloud.com"
authorImage = "images/Avatar.png"
copyright = "Copyright © 2021 - VISIONARY · All rights reserved"
favicon = "favicon.ico"
autoDarkMode = true
paginate = 3
disqusShortname = "visionary"
hideAutoMenu = false
description = """
Call me Mia

There is my development notes.
"""
ignoreErrors = ["error-remote-getjson"]
googleAnalytics = "2701108973"
gtagId = "G-Z0FJ599SKS"
githubUsername = "viisionary"

[params.simpleAnalytics]
enable = true


[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[params.homepage.social]
twitter = "https://twitter.com/visionary_mi"
github = "https://github.com/viisionary"
instagram = "https://www.instagram.com/mia_.min/"
wechat = "/IMG_1958.JPG"
[build]
writeStats = true

[[params.homepage.resume.work]]
# name = "工作经历"
role = "Sr. WEB FRONT END DEVELOPER"
duration = "AUG 2017 - NOW"

[params.homepage.resume]
skills = ["HTML\\ CSS\\ JAVA SCRIPT", "NODE.JS","WEBPACK\\GRUNT","TYPE SCRIPT", "WEB MEDIA"]

[params.homepage.codepen]
username = "viisionary"
pens = ["MWmWVxw","wvrxrww", "RxodrP", "BmXGdm", "wdVypQ",]

[params.homepage.codesandbox]
username = "viisionary"
codesandbox = ["fsk69", "lsmnx"]

#------------- git hub repo
[params.homepage.github]
username = "viisionary"
repos = ["spider-tool", "spider-ui-cli", "spider-cli", "spider-api","deploy2server","spider-generate-api"]

[params.homepage.npm]
username = "visionary_m"
packages = ["spider-utils", "deploy2server", "spider-cli-generater","spider-optimize-svg", "spider-vision",'spider-generate-api']

[params.homepage]
title = "VISIONARY"
tagline = "BLOG"
description = "There is my development notes."
contact = "https://twitter.com/visionary_mi"

