baseURL = "https://visionary.top/"
languageCode = "en-us"
theme = "showfolio"
title = "VISIONARY"
EnableRobotstxt = true
images = ["images/profile.png"]
Paginate = 1000
darkMode = true
ignoreErrors = ["error-remote-getjson"]

[taxonomies]
series = "series"
tag = "tags"
category = "categories"

[params]
name = "Showfolio Theme"
author = "VISIONARY"
authorEmail = "min_0610@icloud.com"
authorImage = "images/Avatar.png"
copyright = "Copyright © 2021 - VISIONARY · All rights reserved"
favicon = "favicon.ico"
autoDarkMode = true
paginate = 3
disqusShortname = "visionary"
hideAutoMenu = false
description = """
Call me Mia

There is my development notes.
"""
ignoreErrors = ["error-remote-getjson"]
googleAnalytics = "2701108973"
gtagId = "G-Z0FJ599SKS"
githubUsername = "viisionary"

[params.simpleAnalytics]
enable = true


[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[params.homepage.social]
twitter = "https://twitter.com/visionary_mi"
github = "https://github.com/viisionary"
instagram = "https://www.instagram.com/mia_.min/"
wechat = "/IMG_1958.JPG"
[build]
writeStats = true
#[[params.homepage.resume.courses]]
#name = "Design Principles"
#provider = "UX Academy"
#duration = "Nov 2019 - Jan 2020"

#[[params.homepage.resume.work]]
#name = "工作经历"
#role = "Sr. UX Designer"
#duration = "Jan 2016 - Oct 2019"

#[[params.homepage.resume.work]]
#name = "Google"
#role = "Product Engineer"
#duration = "Nov 2019 - Apr 2021"
[params.homepage.resume]
skills = ["HTML", "CSS", "JAVA SCRIPT", "NODE.JS"]

[params.homepage.codepen]
username = "viisionary"
pens = ["poPeNKa", "RxodrP", "BmXGdm", "wdVypQ", "wdVypQ"]

[params.homepage.codesandbox]
username = "viisionary"
codesandbox = ["fsk69", "lsmnx"]

#------------- git hub repo
[params.homepage.github]
username = "viisionary"
repos = ["spider-tool", "spider-cli", "deploy2server"]

[params.homepage.npm]
username = "visionary_m"
packages = ["spider-utils", "deploy2server", "spider-cli-generater"]

[params.homepage]
title = "VISIONARY"
tagline = "BLOG"
description = "There is my development notes."
contact = "https://twitter.com/visionary_mi"

