baseURL = "http://example.org/"
languageCode = "en-us"
theme = "anatole"
title = "VISIONARY BLOG"
EnableRobotstxt = true


[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[params]
contentratio = 0.7
profilePicture = "images/profile.png"
description = """
Call me Mia

There is my development notes.
"""
readMore = true
copyright = "2021-{{ YEAR }}"

displayMode = "dark"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "min_0610@icloud.com"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/mia_.min/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twiitter"
url = "https://twitter.com/visionary_mi"

[[params.socialIcons]]
icon = "fab fa-github"
title = "twiitterdisableComments"
url = "https://github.com/viisionary"

[params.gitalk]
clientID = "4bcefb913150c531befa"
clientSecret = "5dc4b021b4783a761f92a5d73f984c2fae0cfeda"
repo = "https://github.com/viisionary/blog"
owner = "viisionary"
admin = "viisionary"
#id= "location.pathname" # The unique id of the page.
#labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
#perPage= 15 # Pagination size, with maximum 100.
#pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
#createIssueManually= false # If it is 'false', it is
