baseURL = "http://example.org/"
languageCode = "en-us"
theme = "showfolio"
title = "VISIONARY BLOG"
EnableRobotstxt = true
images = ["site-feature-image.jpg"]
Paginate = 1000
darkMode = true

[taxonomies]
series = "series"

[params]
name = "Showfolio Theme"
author = "VISIONARY"
authorEmail = "name@example.com"
authorImage = "images/profile.png"
copyright = "Copyright © 2021 - VISIONARY · All rights reserved"
favicon = "favicon.ico"
autoDarkMode = true
paginate = 3
hideAutoMenu = false
profilePicture = "images/profile.png"
description = """
Call me Mia

There is my development notes.
"""
readMore = true
disqusShortname = "visionary"
googleAnalytics = "UA-123-45"
gtagId = "G-Z0FJ599SKS"

[params.simpleAnalytics]
enable = true

[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

#----------
[params.homepage.social]
twitter = "https://twitter.com/"
linkedin = "https://linkedin.com/in/"
github = "https://github.com/viisionary"
medium = "https://medium.com/"
reddit = "https://reddit.com/"
dribbble = "https://dribbble.com/"

[build]
writeStats = true
[[params.homepage.resume.courses]]
name = "Design Principles"
provider = "UX Academy"
duration = "Nov 2019 - Jan 2020"

[[params.homepage.resume.work]]
name = "Amazon"
role = "Sr. UX Designer"
duration = "Jan 2016 - Oct 2019"

[[params.homepage.resume.work]]
name = "Google"
role = "Product Engineer"
duration = "Nov 2019 - Apr 2021"

[params.homepage.resume]
skills = ["Visual Design", "Product Development"]
[params.homepage.codepen]
username = "viisionary"
pens = ["poPeNKa", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage]
title = "Hey 👋 I'm John Doe"
tagline = "UX Designer and Product Lead"
description = "Develop functional user interfaces and provide a valuable experience to customers."
contact = "https://twitter.com/"
ignoreErrors = ["error-remote-getjson"]
